/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jdsu_simon_mixer_controller_ALSAMixerController */

#ifndef _Included_com_jdsu_simon_mixer_controller_ALSAMixerController
#define _Included_com_jdsu_simon_mixer_controller_ALSAMixerController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jdsu_simon_mixer_controller_ALSAMixerController
 * Method:    controllMixer
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_jdsu_simon_mixer_controller_ALSAMixerController_controllMixer
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
